### ISSUE TITLE
communication

### ISSUE THREAD

**Issue by dkof2002** [TheVisual/DiscordUsernameChecker#1]
I want to contact you, how?

**Comment by TheVisual** [comment]
@dkof2002 are you on forum? if so PM me there if not let me know and ill drop my telegram

**Comment by dkof2002** [comment]
> @dkof2002 are you on forum? if so PM me there if not let me know and ill drop my telegram

I want your telegram

**Comment by TheVisual** [comment]
https://t.me/keyattest
